### PR TITLE
Support for IPython 3.0

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
IPython 3.0 changed a number of kernel related functionality which require updates.  Current commit allow the plugin to find the kernel with the `:IPython` command and monitor the subchannel.  Still need to fix tab completion and test other features.

**Comment by benjaminvdb** [comment]
It sounds like you're doing a fantastic job, jjhelmus! Thanks so much for taking the time. I'm pretty much dependent on vim-ipython, but I don't have much time to tinker with it.

**Comment by jjhelmus** [comment]
All the features I've tested are working on IPython 3.1.0.  Let me know if there is anything I missed.

**Comment by jjhelmus** [comment]
@ivanov Can this be reviewed for possible merging?

**Comment by ivanov** [comment]
this seems reasonable, thanks for pitching in @jjhelmus

**Comment by dajuno** [comment]
Here vim-ipython does not work for vim compiled for python3 (ArchLinux gvim-python3 package). Maybe it's not supposed to work since has('python') is 0, but has('python3') == 1, which I put into the ipy.vim...

```
Error detected while processing /home/david/.vim/bundle/vim-ipython/ftplugin/python/ipy.vim:
line   44:
E319: Sorry, the command is not available in this version: python << EOF
line   45:
E492: Not an editor command: import vim
line   46:
E492: Not an editor command: import sys
"=" [New File]
Cannot open file "="
"vim.eval("expand('/home/david/.vim/bundle/vim-ipython/ftplugin/python')")" [New DIRECTORY]
Cannot open file "vim.eval("expand('/home/david/.vim/bundle/vim-ipython/ftplugin/python')")"
line   47:
E480: No match: _ipython_path
line   48:
E492: Not an editor command: sys.path.append(vim_ipython_path)
line   49:
E492: Not an editor command: from vim_ipython import *
line   51:
E492: Not an editor command: EOF
```

When I used vim compiled with python2, vim-ipython didn't work either for ipython3, telling me that vim and ipython had to be using the same python installation...
So how would it work, then? Suggestions? Thanks!

**Pull request merged**
